export const GETDATA = 'GETDATA';
export const ORDERCURRENTPAGE = 'ORDERCURRENTPAGE';
export const CHANGENAME = 'CHANGENAME';
export const GETFILTER = 'GETFILTER';
export const GETDICTION = 'GETDICTION';
export const SETCURRENTPAGE = 'SETCURRENTPAGE';
export const SETDIALOTITLE = 'SETDIALOTITLE';
export const SETDICTIONS = 'SETDICTIONS';
